name: Deploy Backend to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # 👈 Chuyển từ ubuntu-latest sang self-hosted

    steps:
      - name: Deploy Backend trực tiếp trên server
        run: |
          echo "🚀 Bắt đầu triển khai Backend..."
          cd /home/hoangvietadmin/conghaiso/Conghaiso-backend
          
          echo "🔄 Kéo code mới nhất từ nhánh main..."
          git fetch --all
          git reset --hard origin/main

          echo "📦 Cài đặt các thư viện cần thiết..."
          npm install --production

          echo "🔄 Khởi động lại ứng dụng backend với PM2..."
          pm2 reload ecosystem.config.js --env production
          
          echo "✅ Triển khai Backend thành công!"